### ISSUE TITLE
How to parallel process a single dump

### ISSUE THREAD

**Issue by kilgarenone** [mediawiki-utilities/python-mwxml#17]
If I only had a dump `enwiki-20211020-pages-articles.xml`, and I wanted to parallel process it by following the example [here](https://pythonhosted.org/mwxml/map.html), would it actually parallel process the dump?

```
>>> import mwxml
>>> files = ["enwiki-20211020-pages-articles.xml"]
>>>
>>> def page_info(dump, path):
...     for page in dump:
...         yield page.id, page.namespace, page.title
...
>>> for id, namespace, title in mwxml.map(page_info, files):
...     print(id, namespace, title)
...
```

**Comment by kilgarenone** [comment]
ah i think i have to download 'partitions' of a dump. cool.

**Comment by halfak** [comment]
That's right.  If there is a need to parallel process a single dump file, there are some options that we can explore.  But they are all have bigger tradeoffs than processing the partitioned dumps.

**Comment by kilgarenone** [comment]
Both are possible. I see. Amazing. Thank you for your work :bow:

-------- Original Message --------

**Comment by halfak** [comment]
I'm really happy it is useful :)

**Comment by kilgarenone** [comment]
sorry quick question if I may: Am i correct to assume that i have to decompress each of the `.bz2` files beforehand? 

coz I'm looking at this [tutorial](https://github.com/WillKoehrsen/wikipedia-data-science/blob/master/notebooks/Downloading%20and%20Parsing%20Wikipedia%20Articles.ipynb) where it shows reading lines of compressed dumps with `bzcat`. that saves storage(which is cool coz i happen to be constrained by storage on my pretty old thinkpad..). but i feel the SAX parser cooked up there might not be able to handle edge cases like `mwxml` can. 

i guess what im wondering essentially is: `mwxml` don't happen to support parallel processing compressed dumps, does it?

**Comment by halfak** [comment]
No decompression necessary.  It will streaming decompress the files on the
fly.  Use the map function.

**Comment by kilgarenone** [comment]
Cool!  🙇‍♂️ 🙇‍♂️
