### ISSUE TITLE
Python 2 compatibility

### ISSUE THREAD

**Issue by abuccts** [mediawiki-utilities/python-mwxml#4]
`mwxml` only works on Python 3 at present, e.g. `yield from` in [mwxml/map/map.py](https://github.com/mediawiki-utilities/python-mwxml/blob/master/mwxml/map/map.py#L47) not work in Python 2.
Is there any consideration to make this utility compatible with Python 2?

**Comment by halfak** [comment]
Nope.  Sorry.  Python 2 has been being phased out for more than 10 years.
