### ISSUE TITLE
Unexpected tag error for "DiscussionThreading" tags

### ISSUE THREAD

**Issue by abuccts** [mediawiki-utilities/python-mwxml#5]
[mwxml/iteration/page.py#L86](https://github.com/mediawiki-utilities/python-mwxml/blob/master/mwxml/iteration/page.py#L86) doesn't handle "DiscussionThreading" tags in XML dump, which are legal according to XML schema at [https://www.mediawiki.org/xml/export-0.8.xsd](https://www.mediawiki.org/xml/export-0.8.xsd).

MalformedXML will interrupt the page iteration, which needs to be fixed.

**Comment by halfak** [comment]
Is this something from Flow or is it the old LiquidThreads thing?  I'm trying to figure out where I can get a dump that allows me to test a fix for this.

**Comment by halfak** [comment]
In the meantime, I just submitted https://github.com/mediawiki-utilities/python-mwxml/commit/7846c43fad59699fb9060b6f7048d4bd5d555640 which will cause <discussionthreadinginfo> tags to get skipped so that XML dumps with the tag can still safely be processed.  I think we shouldn't resolve this until the tags are properly handled though.  

`pip install mwxml==0.3.2` should fix your immediate issue (unless you need the information in that tag)

**Comment by abuccts** [comment]
Hi @halfak ,

Thanks for your fix! For testing dump, please check this one [enwiktionary-20170601-pages-articles-multistream.xml.bz2](https://dumps.wikimedia.org/enwiktionary/20170601/enwiktionary-20170601-pages-articles-multistream.xml.bz2).

There are many `<DiscussionThreading>` tags in the dump, the first one has page id `2113483` and title `Thread:User talk:ArielGlenn/lqt test number 1`. It's strange that the tag name is `<DiscussionThreading>` instead of `<discussionthreadinginfo>` which appears in XML schema.

Please use the following commands for a quick look:
```sh
$ grep -A 30 -B 5 "<id>2113483</id>" enwiktionary-20170601-pages-articles-multistream.xml
    </revision>
  </page>
  <page>
    <title>Thread:User talk:ArielGlenn/lqt test number 1</title>
    <ns>90</ns>
    <id>2113483</id>
<DiscussionThreading>
        <ThreadSubject>lqt test number 1</ThreadSubject>
        <ThreadPage>User talk:ArielGlenn</ThreadPage>
        <ThreadID>1</ThreadID>
        <ThreadAuthor>ArielGlenn</ThreadAuthor>
        <ThreadEditStatus>has-reply</ThreadEditStatus>
        <ThreadType>normal</ThreadType>
        <ThreadSignature>[[User:ArielGlenn|ArielGlenn]]</ThreadSignature>
</DiscussionThreading>
    <revision>
      <id>9033408</id>
      <timestamp>2010-05-17T06:11:56Z</timestamp>
      <contributor>
        <username>ArielGlenn</username>
        <id>33073</id>
      </contributor>
      <comment>New thread: lqt test number 1</comment>
      <model>wikitext</model>
      <format>text/x-wiki</format>
      <text xml:space="preserve">here it is, the first lqt thread on en wikt.  Did I break anything? --</text>
      <sha1>oxu9xhsuif5idtzx8k0he872vxbyubf</sha1>
    </revision>
  </page>
  <page>
    <title>min of meer</title>
    <ns>0</ns>
    <id>2113484</id>
    <revision>
      <id>21906521</id>
      <parentid>19657063</parentid>
```

**Comment by abuccts** [comment]
Skipping is OK but current `mwxml==0.3.2` version still can't process the dump safely due to the unmatched tag name. I will open a PR to solve this.
